const Items = [
    {
      id: 1,
      name: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      image: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/51a9c5b156c84977ae50004b5ef622b2/finalFB.jpg',
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      name: 'diner double',
      category: 'lunch',
      price: 13.99,
      image: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/86/9d/db/canada-s-diner-double.jpg',
      description: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      name: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      image: 'https://i2-prod.glasgowlive.co.uk/incoming/article16335490.ece/ALTERNATES/s1200b/0_DSC_5334-copy-1.jpg',
      description: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      name: 'country delight',
      category: 'breakfast',
      price: 20.99,
      image: 'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_312,h_196,c_fill/eenwsasasyeqnq4hlhhm',
      description: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      name: 'egg attack',
      category: 'lunch',
      price: 22.99,
      image: 'http://karthfoodfactory.com/wp-content/uploads/2020/12/10.png',
      description: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      name: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/tim-hortons-oreo-cookie-dream-donut-1593018106.jpg?resize=640:*',
      description: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      name: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      image: 'https://react-projects-5-menu.netlify.app/images/item-7.jpeg',
      description: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      name: 'american classic',
      category: 'lunch',
      price: 12.99,
      image: 'http://cdn.cnn.com/cnnnext/dam/assets/170206144443-taters.jpg',
      description: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      name: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      image: 'https://pbs.twimg.com/media/ET492qwWoAgs2s4.jpg',
      description: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default Items;